import bcrypt from "bcryptjs"; //for hashing the password

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: "Apple iPad 11 Pro",
      slug: "apple-ipad11-pro",
      category: "Tablets",
      image: "/images/p1.jpg", // 679px × 829px
      price: 995,
      countInStock: 10,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality ipad",
    },
    {
      // _id: '2',
      name: "boAt On Ear Headphones",
      slug: "boat-on-ear-headphones",
      category: "Headphones",
      image: "/images/p2.jpg",
      price: 16,
      countInStock: 5,
      brand: "Boat",
      rating: 4.0,
      numReviews: 10,
      description: "high quality headphone",
    },
    {
      // _id: '3',
      name: "Apple 2020 MacBook Air Laptop ",
      slug: "macbook-air-laptop",
      category: "Laptops",
      image: "/images/p3.jpg",
      price: 1189,
      countInStock: 15,
      brand: "Apple",
      rating: 4.5,
      numReviews: 14,
      description: "high quality apple laptop",
    },
    {
      // _id: '4',
      name: "OnePlus 9R 5G",
      slug: "one-plus-9R-5g",
      category: "Mobiles",
      image: "/images/p4.jpg",
      price: 589,
      countInStock: 5,
      brand: "OnePlus",
      rating: 4.5,
      numReviews: 10,
      description: "high quality mobile product",
    },
    {
      // _id: '4',
      name: "Apple 2022 11-inch iPad Pro ",
      slug: "apple-2022-ipad-pro",
      category: "Tablets",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Ipad",
    },
  ],
};
export default data;
